apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-weather
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weatherapp-weather
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weatherapp-weather
    spec:
      containers:
      - name: weatherapp-weather
        image: afakharany/weatherapp-weather:lab
        imagePullPolicy: IfNotPresent
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              key: apikey
              name: weather
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http 
        readinessProbe:
          httpGet:
            path: /
            port: http 
