
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-weather
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: weatherapp-weather
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: http